<!--
This is for including Chapter 1.  Notice that it's also good practice to name your chunk.  This will help you debug potential issues as you knit.  The chunk above is called intro and the one below is called chapter1.  Feel free to change the name of the Rmd file as you wish, but don't forget to change it here from chap1.Rmd.
-->

<!--
The {#rmd-basics} text after the chapter declaration will allow us to link throughout the document back to the beginning of Chapter 1.  These labels will automatically be generated (if not specified) by changing the spaces to hyphens and capital letters to lowercase.  Look for the reference to this label at the beginning of Chapter 2.
-->

# Environmental Justice {#env_justice}

## Environmental Justice Theories
This growing body of environmental literature has shown with increasing certainty that on average minorities in America experience a higher poullution level than the white population. The literature has focused primarily on air pollution and industrial facilities, the two areas with the most consistently accessible data. Many authors have focused on point source pollution, measuring individual pollution as a binary: the presence or absence of a polluting facility in the geographic level of analysis (SOURCE). An alternate measure of pollution has been a 

The expected trends in toxicity for the global population . Approaches to the idea of environmental justice are not ????, many approach the issue from the context of point source pollution (SOURCES), some use data on transportation emissions, and others use broader environmental data, like levels of NO2 and PM2.5. Results are not unanimous. Many studies conclude that minorities do experience a disproportionate toxicity or pollution burden (SOURCES), others find that economic class accounts for most of the difference in experienced toxicity (SOURCES), yet others find no racial differences (Anderson). 

Environmental justice research is unique in that research and advocacy have gone hand in hand, leading to questions guided by the needs of communities. This trend has led to unusually focused work, evaluating specific communities for the presence of specfic toxins at specific times (SOURCE). Though some work has had a broader net, few authors have broached national data (SOURCES) and even fewer have used data spanning significant time (SOURCES). Due to the definitions of pollution being used, uncertainty in accessible pollution data, and differing geographic units of analysis, work spanning broader time periods as well as a wider geographic range is neccessary to try to understand processes that operate on a national scale that lead to environmental inequality.

Despite differing conclusions from the collective body of research, how we define and think about environmental justice is evolving. Alongside descriptive studies that investigate specific pollution trends, theories of how environmental injustices are created have arisen. The main theorized explanations for environmental injustice are economic, sociopolitical and discriminatory explanations. 

- what is the overall trend in toxicity, do we expect to see that same trend for everyone?
- those studies are not unanimous, but many show a different in group toxicity

### Economic Explanations

Theories focusing on economic explanations for environmental inequality rely on individual rational choice as an explanation. Especially in the case of point source pollution, companies must make economically rational decisions when siting facilities. Those decisions can be multifaceted: if the location has easy access to transportation, or is close to raw materials, but a primary concern is cost of land. Given companies want cheap land for polluting facilities, and minority communities tend to be near cheap land (SOURCE), it's rational that there would be more facility siting in minority areas. 

In the same vein, it would be economically rational for those with the means to escape newly sited pollution to do so. Under this theory, cheaper land is more likely to be near minority communities, those who can afford to escape do so, devaluing the land further, and making it all the more attractive for facility siting. This theory should be testable, given the direct cause and effect theorized, but results have been mixed. Several studies found that more facilities were sited in minority communities (SOURCES), while others didn't (SOURCES).

- low income is not a protected class, so there is no legal recourse to this. 

### Sociopolitical Explanations

An alternate explanation still relies upon siting decisions, but more explicitly exploitative. Sociopolitical explanations theorize that companies rationaly chose to site in minority communities, as they will provide less resistance. At risk communities would show a lower voter turnout, would have a large older population, may be disproportionately renters, and may be poorly politically represented. In theory, communities with lower organizing potential are more attractive for facility siting, as they pose a low risk of creating political or economic resistence to the proposed facility. 

### Racial Discrimination

Racial discrimination theories are divided in to overt and insitutional racism theories. In discussion of these theories the language used tends to change, using the term 'environmental racism' rather than 'environmental justice'. 

The overt discrimination theory speculates on the intentions of the individuals making the final siting decisions. In this case, overt racism refers to the siting decisions as choices made intentionally to cause strife to minority communities. On the flip side of the coin, but the same outcoem, it can refer to the siting choices as deicisons made in order to protect wealthy white communities. 

The intstitutional discrimination theory relies primarily on housing dynamics. Based on the knowledge that the number of minority individuals living near a sited facility has risen since first measured (SOURCE), the theory states that minorities move towards polluting facilities due to reduced choice in the housing market. Reduced choice can arise in several ways: the choices realtors make in showing homes or the availability of mortgages or loans. Local governments can compound the problems with housing availability for minorities, as minority areas are more likely to be rezoned for industrial purposes by local government (SOURCE). 

These three theories all boil down to the same outcome. Despite using different language and justifications all represent different orders of instutional discrimination. Economic explanations rely on the segregation of minority communites created by redlining. Redlining destroyed investment in communities, prevented black families from investing in homes, and enforced segregated communities. Redlining created the geography and culture that enables economic and sociopolitical explanation, making it just a consequence of previous overt discrimination.

Though the current theories of siting choices would all create the same behaviour, the different reasonings can help to explain (and perhaps change) the trends that lead to environmental injustice. 


## Goals 
- address the first question of ej literature by (with this new+improved data, over a longer period of time than analyzed in any of the literature) by looking at how the groups differ, and how that changes over time.
-improve by using accurate measures of location (not people within range of TRI, not amount of pollution, but the toxicity of the pollution experienced by ppl)
- what is the relative toxicity experienced by minority groups over this time period
- how protective are finances?
- 

~~~~~~

Pollock and Vittas argues that potential exposure should be modeled as logarithmic rather than linear function of distance. Looked at the census blocks near TRI facilities. 
TRI siting is commonly related to industrialization/urbanization
"environmental racism" v "enviromental justice" v "environmental inequality"
"ways environmental risks are unequally distributed in society"
Zimmerman 1993 differences are "largely attributable to the correlation of minority populations in a few large urban areas with NPL sites"
'Race is the single most accurate prdictore of the location of hazardous waste sites' -VP al gore
"after the industrial accident at the Union Carbinde plant in India ... also being produced in the US unbeknown to local residents, Congress added a new provison to the Superfund law, the community right to know act, mandating that industry report annual releases of over 300 toxic substances"
"TRI data are a minuscule and severely skewed selection of all emisisons... less than 1 percent of all wastes generated" (1995:28)
'Move beyond measures of presence/absence of emissions and beyond number of facilities.'
'Even when serious inequities are found, such work is of little help in explaining how ithappened.'
"Thre relationship between demographics and unequal exposure is most elusive in national-level studies, but shows up consistently in smaller-scale studies."
"Plagued by lack of data on where all the hazards are, uncertainties about rate and direction of dispersion, as well as finally uncertainties about the actual health effects in those who are exposed."
"They are social relations that interact in complex ways.. ej literature sets up race and class as airtight things that can be isolated, both conceptually and methodologically"
"Neglected topic #1: Where is the Bourgeoisie?"


MIGRATION RACE AND ENVIRONMENTAL HAZARDS
"researchers have studied the distribution of social groups around a variety of environmental hazards"
"leave open questions about the overall magnitude of environmental racial inequality, providing dramatically different estimates of racial/ethnic disparities in proximity and exposure to environmental hazards."
"microlevel mechanisms through which aggregate patterns of environmental racial inequality develop and are maintained"
"competeing theoretical arguments in the environmental justice literature"

* Fisher J. B., Kelly M. & Romm J. (2006). Scales of environmental justice: Combining GIS and spatial analysis for air toxics in West Oakland, California. *Health & Place, 12*, pp. 701-714.
    * Uses data from the ISCST3 air dispersion model, and local knowledge of non-point soureces of diesel emissions in West Oakland.
    * Does a disparate impact analysis based on the EPA's 
    * Proves that the point sources are not randomly dispersed accros the Bay area, let alone the Oakland area, and shows statistically significant clusters of facilities. 

* Kravitz-Wirtz N., Crowder K., Hajat A. & Sass V. (2016). The Long-term Dynamics of Racial/Ethnic Inequality in Neighborhood Air Pollution Exposure, 1990-2009. *Du Bois Review, 13*(2), pp. 237-259.
    * Uses data from the Panel Study of Income Dynamics (PSID), and data on nitrogen dioxide (NO2), and particulate matter (PM2.5 and PM10) from the Toxic Resource Inventory (TRI) and the Air Quality System (AQS).
    * Find that "Blacks and Latinos are, on average, more likely to be exposed to higher levels of NO2, PM2.5, and PM10 than Whites."
    * More specifically, examines the "correspondence between neighborhood racial composition and pollution levels" using the household level data in PSID.
    * Additionally uses measures of population density and residential segregation (measured using multigroup entropy index) of the areas each of the households are located in. 
    * Uses a multilevel repeated measures model. Level 1 is individual intercepts and slopes, Level 2 is the average of all intercepts and slopes, with coefficients for race and time, Level 3 accounts for metropolitan areas. 
    * Conclusions: There are substantial racial differneces in exposure to several kinds pollution. This persists even for households in similar circumstances. Declines in pollution over time have gone predominantly to minority groups. 
    * Future work: Disentangle if differences come from "racially distinct patterns of individual mobility", "neighborhood change", or industrial siting. 

* Gilbert A. & Chakraborty, J. (2011). Using geographically weighted regression for environmental justice analysis: Cumulative cancer risks from air toxics in Florida. *Social Science Research, 40*, pp. 273-286.

* Ard K. (2015). Trends in exposure to industrial air toxins for different racial and socioeconomic groups: A spatial and temporal examination of environmental inequality in the U.S. from 1995 to 2004. *Social Science Research, 53*, pp. 375-390.

* Burwell-Naney K. et al. (2013). Spatial disparity in the distribution of superfund sites in South Carolina: an ecological study. *Environmental Health, 12*(1).

* Moghadam A. K. & Kayahan B. (2017). What influences the pattern of pollutant releases? An investigation of firms' siting and households' sorting decisions in Ontario, Canada. *Journal of Environmental Planning and Management, 60*(4). pp. 743-754.

* Pais J., Crowder K. & Downey L. (2013). Unequal Trajectories: Racial and Class Differences in Residential Exposure to Industrial Hazard. *Social Forces, 92*(3). pp. 1189-1215
