# Data {#math}

## Raw Data

The Risk Screening Environmental Indicators (RSEI) Model is a geographically detailed data set produced by the Environmental Protection Agency (EPA). RSEI is based upon the Toxic Release Inventory (TRI), which (for about 30 years) has been collecting data on all toxic releaases in the US. The TRI program manages the regulations, policies and facilities that are ultimately reported. 

TRI data is self reported by facilities, with each observation being a release of a reporting facility for a reporting chemical. For each observation, data is collected on which chemical was released, how much of it was released, and the specific facility from which it was released. 

The detailed location and chemical data that is collected through TRI, as well as detailed weather data from NOAA is reformatted through a fate and transport model. The RSEI data shows where each release has traveled on an 800m grid across the USA. The ultimate data we have access to through the RSEI data is an observation for each release, for each square in the grid the release hits. This gives us an idea of how the chemicals spread from the release locations, and enables us to create a map across the entire nation for where TRI chemicals are at any time between 1988 and 2014. 

## Important Caveats

Due to the nature of the data, there are a few interesting caveats to consider. 

* The RSEI data is self reported, and has been thought to contain some severe underreporting. 

* The data is entirely based off a black box fate and transport model. The model has uncertainty that we are not addressing. 

* The data only captures releases from certain industries, for certain facility types within those industries, for certain chemical types within those facilities. Not all chemicals are mandated reporting, and any analysis that is done based off the data can't be extrapolated to discuss toxicity more generally. 

* Not only does the data not capture all chemicals, it also doesn't broach many common nuicances, both enviromental and toxic. Because of this, it is difficult to relate the RSEI scores to health outcomes in an area. In discussion of environmental toxicity, it is worth noting that certain toxicity types may not present themselves as easily (eg. may or may not reach local water systems). There are also more obvious environmental hazards, that are likely to have strong influence on public health and living conditions that TRI doesn't address, eg: brownfields, solid waste disposal, animal farming, hazardous waste, etc.

* RSEI gives the weight of the release and the chemical of the release, but chemicals have very different levels of toxicity. To that end, the EPA assigned each chemical a 'toxicity' weight, by which the amount of the chemical is multiplied. This means that we can aggregate all the chemicals in an area, and compare the overall toxicity over space and time. The toxicity weights allow us to compare to other chemicals' toxicity weight, and overall toxicity of a given chemical release, but also means that the values only have meaning in comparison.

Despite the limitations that the data presents, it provides an incredibly detailed and complex view of toxicity in America that is worth delving in to. 

## Consistency in Reporting (detailed data description)

### Census Comparability

For the time period that RSEI data is available during (1988 - 2014), Census geographies have experienced considerable overhaul. Many of our questions of interest involve demographic characteristics, and the changes we see in environmental toxicity over time for those demographics. As such, we need to be able to aggregate the toxicity to block group or tract level to be able to merge with Census data. To do so, we caluclate the toxicity values for each geographic unit for the closest temporal census geography (1990, 2000 or 2010).

### Details of Chemical Consistency

Comparability across time, space, and chemicals is a consistent topic through this section. The EPA is incredibly detailed in their data collection, and creation of metrics to make the data meaningful on a broad scale. Unfortunately the EPA is subject to the changing scientific consensus of the times, and therefore hasn't been able to provide entirely consistent data. 

Over time, as chemicals have been found to be toxic, they have been added to the list of chemicals that on the list of TRI mandated reporting. There are also chemicals that through renewed understanding have been removed from the mandated reporting list. Because the list of chemicals reported changes over time, aggregating all the data would cause us to see artificial jumps in toxicity, especially likely in large manufacturing centers. These jumps wouldn't be reflective of an actual increase in toxicity, but rather that the toxicity was beginning to be measured. 

Using the consistent_chemicals table provided by Rich Puchalsky, the chemicals that are relevant to the specific years of interest are calculated in the runDatabase.R file in the define_consistent_chemicals function. They are found by selecting the subset of chemicals where the year of initial regulation is before the interest period, and the year of deregulation is after the interest period, while also excluding delisted chemicals. 

### Details of Industry Reporting Consistency

the TRI regulates who needs to self report using the North American Industry Classification System (NAICS), and before that the Standard Industrial Classification (SIC) system. Just as we see changes in the regulations for chemicals, we see changes in the regulations of various industries. NAICS codes are regulated independently of chemical codes, and NAICS codes that are not consistently reported across the time period of interest must be removed to maintain continuity. For a toy example, a textiles facility releasing mercury might have to report it, but the neighboring mining facility might not. If that changes over the time period, and suddenly mining needs to report, we will see an artificial huge jump in the mercury present in that area if we don't remove by industry.

A data complication arises in that the only reference to NAICS or SIC codes are in the facility table that the releases reference. This table provides 6 NAICS codes that are the most common NAICS codes associated with the production of the facility. However, NAICS codes are release specific, not facility specific, meaning that for each emission reported a NAICS code is reported. Removing by facility is not accurate, since facilities might have different types of NAICS emissions. The textiles facility we used as an example earlier might make both shoes and jackets, with different industry codes and different releases that have different reporting requirements.

To get data on the NAICS codes by submission, data must be taken from the original TRI data, and linked to the disaggregated microdata by the document control number.


## Ultimate Data Form

The initial data from RSEI is in the form of one observation per release per block on the 800m grid that it reached. Given that the 800m grid across the United States has on the order of 10 billion squares, each release hits many squares, we have many releases, and the data covers 27 years, this is an enormous data set. Overall, the disaggregated microdata is approximately 4 terabytes of data. 

In the data cleansing process, we filter the data to remove industries and chemicals that were not consistent over the period of inquiry, and aggregate the data to the relevant Census geographies. The data, after an extensive and computationally intesive process, forms a data set with an observation for each year, for each block group/tract, with just one measure, an aggregated toxicity level. 

The pollution estimate must be interpreted in the context of the consistency adjustments. For example, towns with extremely high mining emissions may not show as exceptionally high pollution, as mining is one of the industries that had different regulations over the 1990-2010 time period, and therefore the reported mining emissions have been removed entirely. Essentially, the pollution estimates are comparable across time and location, but only in the context of continuous EPA regulation. 