# Goals {#goals}

This work aims to address some of the limitations of the current environmental justice literature by examining a comprehensive dataset that covers the entire nation, with data spanning from 1988 to 2015. The broad temporal and spatial coverage is nearly unparalleled in environmental justice literature, with the last study of this length spanning the years 1970 to 1994 (Been and Gupta, 1997), relying solely upon tract level hazardous waste site data. 

The goals of this paper are:

* To build empirical distributions of toxicity experienced by the American public. Using those distributions to find empirical 5^th^, 50^th^, and 95^th^ percentiles of experienced toxicity for white, black, and Hispanic populations over time. Rather than examining the mean of each group, these percentiles give us an idea of which groups have access to areas with low toxicity, which groups are most at risk for extreme toxicity (which is most likely to relate to lifestyle or health effects,) and an idea of how the median changes for each group. 

* Simulating how minority distributions would look in 2015 given they had held constant their relative position in the overall distribution of 1990. This measure allows us to see how much of the improvement in relative toxicity is attributable to the compression of the overall toxicity distribution, and how much is attributable to changes in the relative state of minority groups. 

* To create a web app that provides a searchable map database with information on local toxicity, and the local state of environmental justice. The goal of this app is to make complex data accessible for public use. 
