```{r, include = FALSE}
library(readr)
library(ggplot2)
library(dplyr)
library(plyr)
library(spatstat)
library(choroplethrMaps)
library(choroplethr)
library(devtools)
#devtools::install_github("amd112/rseiAnalysis")
#library("rseiAnalysis")
```

# Approaches and Methods {#ref-labels}

```{r, include = FALSE}
t1990 <- read_csv("data/toxic_1990_1990_blockgroup.csv")
t1990$block = substr(t1990$block, 2, 12)
c1990 <- read_csv("data/LTDB_Std_1990_fullcount.csv")
t1990 = merge(t1990, c1990, by.x = "block", by.y = "TRTID10")
t1990$lconcentration = log(t1990$concentration)
t1990 = select(t1990, block, lconcentration, concentration, POP90, NHWHT90, NHBLK90, HISP90, OWN90, RENT90)
names(t1990) = c("block", "lconcentration", "concentration", "tot_pop", "white", "black", "hispanic", "owners", "renters")
t2000 <- read_csv("data/toxic_2000_2000_blockgroup.csv")
#t2000 = aggregateGeography(t2000, "tract")
c2000 <- read_csv("data/LTDB_Std_2000_fullcount.csv")
t2000 = merge(t2000, c2000, by.x = "block", by.y = "TRTID10")
t2000$lconcentration = log(t2000$concentration)
t2000 = select(t2000, block, lconcentration, concentration, POP00, NHWHT00, NHBLK00, HISP00, OWN00, RENT00)
names(t2000) = c("block", "lconcentration", "concentration", "tot_pop", "white", "black", "hispanic", "owners", "renters")
t2010 <- read_csv("data/toxic_2010_2010_blockgroup.csv")
#t2010 = aggregateGeography(t2010, "tract")
c2010 <- read_csv("data/LTDB_Std_2010_fullcount.csv", col_types = cols(tractid = col_character()))
c2010$tractid = str_pad(c2010$tractid, 11, pad = "0")
t2010 = merge(t2010, c2010, by.x = "block", by.y = "tractid")
t2010$lconcentration = log(t2010$concentration)
t2010 = select(t2010, block, lconcentration, concentration, pop10, nhwht10, nhblk10, hisp10, own10, rent10)
names(t2010) = c("block", "lconcentration", "concentration", "tot_pop", "white", "black", "hispanic", "owners", "renters")
```

```{r}
#nonParametricExtrapolate(t2010, t1990)

```

testing testing 

123