# Results {#organization}



## Toxicity trends over time

```{r quantileCalcs, echo = FALSE, message = FALSE, warning = FALSE}
library(plyr)

sim05 = fread("data/simulation05.csv", data.table = FALSE)
sim50 = fread("data/simulation50.csv", data.table = FALSE)
sim95 = fread("data/simulation95.csv", data.table = FALSE)
se_race_05 = fread("data/bootstrap_race_se_05.csv", data.table = FALSE)
se_race_50 = fread("data/bootstrap_race_se_50.csv", data.table = FALSE)
se_race_95 = fread("data/bootstrap_race_se_95.csv", data.table = FALSE)

get_perc = function(data, quant, variables = c("white", "black", "hispanic", "other"), sim = NA, se = NA) {
  new = sort(unique(data$year), decreasing = FALSE)
  for (var in variables) {
    new = cbind(new, ddply(data, .(year), function(x) weighted.quantile(x$concentration, x[, var]/sum(x[, var]), quant, na.rm = TRUE))[, 2])
  }
  new = as.data.frame(new)
  names(new) = c("year", variables)
  if (!is.na(sim)) {
    new = merge(new, sim, by = "year")
  }
  if (!is.na(se)) {
    new = merge(new, se, by = "year")
  }
  return(new)
}

perc05 = get_perc(data, 0.05, variables = names(data)[c(3:7, 10:18)], sim = sim05)
perc50 = get_perc(data, 0.50, variables = names(data)[c(3:7, 10:18)], sim = sim50)
perc95 = get_perc(data, 0.95, variables = names(data)[c(3:7, 10:18)], sim = sim95)

msa_perc05 = get_perc(dense_data, 0.05, variables = names(data)[c(3:7, 10:18)], sim = sim05)
msa_perc50 = get_perc(dense_data, 0.50, variables = names(data)[c(3:7, 10:18)], sim = sim50)
msa_perc95 = get_perc(dense_data, 0.95, variables = names(data)[c(3:7, 10:18)], sim = sim95)
```

```{r plottingQuantiles, echo = FALSE, message = FALSE, fig.width=8, fig.height=4}
tox = function(cur_data, perc, legend = FALSE, smooth = FALSE, log = TRUE) {
  g = ggplot(data = cur_data) + 
  geom_line(aes(x = year, y = white, color = "white")) +
  geom_line(aes(x = year, y = black, color = "black")) + 
  geom_line(aes(x = year, y = hispanic, color = "hispanic")) + 
  geom_line(aes(x = year, y = other, color = "other")) + 
  labs(x = "Year", y = "Toxicity", title = paste0(perc, "th PCTL Group Toxicity"))
  if (legend == FALSE) {
    g = g + guides(color = FALSE)
  }
  if (smooth == TRUE) {
    g = g +
      geom_line(aes(x = year, y = rollmean(black, 3, na.pad=TRUE), color = "black"), se = FALSE, size = 0.5, linetype = "twodash")  +
      geom_line(aes(x = year, y = rollmean(hispanic, 3, na.pad = TRUE), color = "hispanic"), se = FALSE, size = 0.5, linetype = "twodash") +
      geom_line(aes(x = year, y = rollmean(other, 3, na.pad = TRUE), color = "other"), se = FALSE, size = 0.5, linetype = "twodash") +
      geom_line(aes(x = year, y = rollmean(white, 3, na.pad = TRUE), color = "white"), se = FALSE, size = 0.5, linetype = "twodash")
  }
  if (log == TRUE) {
    g = g + scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),
                          labels = scales::trans_format("log10", scales::math_format(10^.x))) +
      annotation_logticks(
        short = unit(.5,"mm"),
        mid = unit(2,"mm"), 
        long = unit(3.5,"mm"),
        sides = "l",
        color = "gray65") 
  }
  g
}

relative_tox = function(data, perc, legend = FALSE, smooth = FALSE) {
  g = ggplot(data) +
    labs(x = "Year", y = "Toxicity Relative to White Dist.", title = paste0(perc, "th PCTL Toxicity Relative to White Distribution"), colour = "Legend")
  if (smooth == TRUE) {
    g = g + 
      geom_line(aes(x = year, y = (white/white), color = "white")) +
      geom_line(aes(x = year, y = (black/white), color = "black"), alpha = 0.3)  +
      geom_line(aes(x = year, y = (hispanic/white), color = "hispanic"), alpha = 0.3) +
      geom_line(aes(x = year, y = (other/white), color = "other"), alpha = 0.3) +
      geom_line(aes(x = year, y = rollmean(black/white, 3, na.pad=TRUE), color = "black"), linetype = "twodash", size = 0.7)  +
      geom_line(aes(x = year, y = rollmean(hispanic/white, 3, na.pad = TRUE), color = "hispanic"), linetype = "twodash", size = 0.7) +
      geom_line(aes(x = year, y = rollmean(other/white, 3, na.pad = TRUE), color = "other"), linetype = "twodash", size = 0.7) +
      theme(legend.position="bottom")
  }
  else {
    g = g + 
      geom_line(aes(x = year, y = (white/white), color = "white")) +
      geom_line(aes(x = year, y = (black/white), color = "black"))  +
      geom_line(aes(x = year, y = (hispanic/white), color = "hispanic")) +
      geom_line(aes(x = year, y = (other/white), color = "other")) +
      theme(legend.position="bottom")
  }
  if (legend == FALSE) {
    g = g + guides(color = FALSE)
  }
  g
}

pov_tox = function(cur_data, perc, legend = FALSE) {
  g = ggplot(data = cur_data) + 
  geom_line(aes(x = year, y = whiteh, color = "white")) +
  geom_line(aes(x = year, y = blackh, color = "black")) + 
  geom_line(aes(x = year, y = nativeh, color = "native")) + 
  geom_line(aes(x = year, y = asianh, color = "asian")) + 
  geom_line(aes(x = year, y = otherh, color = "other")) + 
  geom_line(aes(x = year, y = whitel, color = "white")) +
  geom_line(aes(x = year, y = blackl, color = "black")) + 
  geom_line(aes(x = year, y = nativel, color = "native")) + 
  geom_line(aes(x = year, y = asianl, color = "asian")) + 
  geom_line(aes(x = year, y = otherl, color = "other")) + 
  labs(x = "Year", y = "Group Toxicity", title = paste0(perc, "th PCTL Toxicity"), color = "Legend")
  if (legend == FALSE) {
    g = g + guides(color = FALSE)
  }
  g
}

g_legend = function(a.gplot) {
  tmp = ggplot_gtable(ggplot_build(a.gplot))
  leg = which(sapply(tmp$grobs, function(x) x$name) == "guide-box")
  legend = tmp$grobs[[leg]]
  return(legend)
}
```

```{r plotGroup05, echo = FALSE, fig.width=10, fig.height=4, warning = FALSE, message = FALSE}
five = tox(perc05, 5)
fifty = tox(perc50, 50)
ninetyfive = tox(perc95, 95)

five_rel = relative_tox(perc05, 5, smooth = TRUE)
fifty_rel = relative_tox(perc50, 50, smooth = TRUE)
ninetyfive_rel = relative_tox(perc95, 95, smooth = TRUE)

legend_grab = relative_tox(perc05, 5, legend = TRUE)
color_legend = g_legend(legend_grab)

grid.arrange(arrangeGrob(five, five_rel, nrow=1),
             color_legend, nrow=2,heights=c(10, 1))
```

```{r, echo = FALSE, fig.width=10, fig.height=4, warning = FALSE, message = FALSE}
grid.arrange(arrangeGrob(fifty, fifty_rel, nrow=1),
             color_legend, nrow=2,heights=c(10, 1))
```

```{r, echo = FALSE, fig.width=10, fig.height=4, warning = FALSE, message = FALSE}
grid.arrange(arrangeGrob(ninetyfive, ninetyfive_rel, nrow=1),
             color_legend, nrow=2,heights=c(10, 1))
```

## Simulating Changes

```{r, echo = FALSE, fig.width=10, fig.height=4}
sim_tox = function(cur_data, perc, legend = FALSE, smooth = FALSE, log = TRUE) {
  g = ggplot(data = cur_data) + 
        labs(x = "Year", y = "Toxicity", title = paste0(perc, "th PCTL Group Toxicity"))
  if (smooth == TRUE) {
    g = g +
      geom_line(aes(x = year, y = white, color = "white"), alpha = 0.3) +
      geom_line(aes(x = year, y = black, color = "black"), alpha = 0.3) + 
      geom_line(aes(x = year, y = hispanic, color = "hispanic"), alpha = 0.3) + 
      geom_line(aes(x = year, y = other, color = "other"), alpha = 0.3) + 
      geom_line(aes(x = year, y = rollmean(black, 3, na.pad=TRUE), color = "black"), size = 0.5)  +
      geom_line(aes(x = year, y = rollmean(hispanic, 3, na.pad = TRUE), color = "hispanic"), size = 0.5) +
      geom_line(aes(x = year, y = rollmean(other, 3, na.pad = TRUE), color = "other"), size = 0.5) +
      geom_line(aes(x = year, y = rollmean(white, 3, na.pad = TRUE), color = "white"), size = 0.5)
  } 
  else {
     g = g +
      geom_line(aes(x = year, y = white, color = "white")) +
      geom_line(aes(x = year, y = black, color = "black")) + 
      geom_line(aes(x = year, y = hispanic, color = "hispanic")) + 
      geom_line(aes(x = year, y = other, color = "other"))
  }
  g = g + geom_line(aes(x = year, y = sim_b, color = "black"), linetype = "dashed", size = 0.7) + 
    geom_line(aes(x = year, y = sim_o, color = "other"), linetype = "dashed", size = 0.7) +
    geom_line(aes(x = year, y = sim_h, color = "hispanic"), linetype = "dashed", size = 0.7) 
  if (legend == FALSE) {
    g = g + guides(color = FALSE)
  }
  if (log == TRUE) {
    g = g + scale_y_log10(breaks = scales::trans_breaks("log10", function(x) 10^x),
                          labels = scales::trans_format("log10", scales::math_format(10^.x))) +
      annotation_logticks(
        short = unit(.5,"mm"),
        mid = unit(2,"mm"), 
        long = unit(3.5,"mm"),
        sides = "l",
        color = "gray65") 
  }
  g
}

relative_sim = function(data, perc, legend = FALSE, smooth = FALSE) {
  g = ggplot(data) 
  if (smooth == TRUE) {
    g = g + 
      geom_line(aes(x = year, y = (white/white), color = "white")) +
      geom_line(aes(x = year, y = (black/white), color = "black"), alpha = 0.3)  +
      geom_line(aes(x = year, y = (hispanic/white), color = "hispanic"), alpha = 0.3) +
      geom_line(aes(x = year, y = (other/white), color = "other"), alpha = 0.3) +
      labs(x = "Year", y = "Toxicity Relative to White Dist.", title = paste0(perc, "th PCTL Toxicity Relative to White Distribution"), colour = "Legend") +
      geom_line(aes(x = year, y = rollmean(black/white, 3, na.pad=TRUE), color = "black"), linetype = "twodash", size = 0.7)  +
      geom_line(aes(x = year, y = rollmean(hispanic/white, 3, na.pad = TRUE), color = "hispanic"), linetype = "twodash", size = 0.7) +
      geom_line(aes(x = year, y = rollmean(other/white, 3, na.pad = TRUE), color = "other"), linetype = "twodash", size = 0.7) 
      geom_line(aes(x = year, y = rollmean(sim_b/white, 3, na.pad = TRUE), color = "black"), linetype = "dashed", size = 0.7) + 
      geom_line(aes(x = year, y = rollmean(sim_o/white, 3, na.pad = TRUE), color = "other"), linetype = "dashed", size = 0.7) +
      geom_line(aes(x = year, y = rollmean(sim_h/white, 3, na.pad = TRUE), color = "hispanic"), linetype = "dashed", size = 0.7) +
      theme(legend.position="bottom")
  } else {
    g = g + 
      geom_line(aes(x = year, y = (white/white), color = "white")) +
      geom_line(aes(x = year, y = (black/white), color = "black"), alpha = 0.45)  +
      geom_line(aes(x = year, y = (hispanic/white), color = "hispanic"), alpha = 0.45) +
      geom_line(aes(x = year, y = (other/white), color = "other"), alpha = 0.45) +
      geom_line(aes(x = year, y = sim_b/white, color = "black"), linetype = "dashed", size = 0.7) + 
      geom_line(aes(x = year, y = sim_o/white, color = "other"), linetype = "dashed", size = 0.7) +
      geom_line(aes(x = year, y = sim_h/white, color = "hispanic"), linetype = "dashed", size = 0.7) +
      labs(x = "Year", y = "Toxicity Relative to White Dist.", title = paste0(perc, "th PCTL Toxicity Relative to White Distribution"), colour = "Legend") +
      theme(legend.position="bottom")
  }
  if (legend == FALSE) {
    g = g + guides(color = FALSE)
  }
  g
}

grid.arrange(arrangeGrob(sim_tox(perc05, 5), relative_sim(perc05, 5), nrow=1),
             color_legend, nrow=2,heights=c(10, 1))
grid.arrange(arrangeGrob(sim_tox(perc50, 50), relative_sim(perc50, 50), nrow=1),
             color_legend, nrow=2,heights=c(10, 1))
grid.arrange(arrangeGrob(sim_tox(perc95, 95), relative_sim(perc95, 95), nrow=1),
             color_legend, nrow=2,heights=c(10, 1))
```

```{r, warning = FALSE,echo = FALSE, fig.width=10, fig.height=4}
ggplot() + 
  geom_density(aes(log(concentration), weight = white/sum(white), fill = "1990", color = "1990"), alpha = 0.4, data[data$year == 1990, ]) +
  geom_density(aes(log(concentration), weight = white/sum(white), fill = "2000", color = "2000"), alpha = 0.4, data[data$year == 2000, ]) +
  geom_density(aes(log(concentration), weight = white/sum(white), fill = "2010", color = "2010"), alpha = 0.4, data[data$year == 2010, ]) +
  labs(x = "Log of Concentration", y = "Density", fill = "Legend") +
  guides(color = FALSE) + xlim(-6, 20)

ggplot() + 
  geom_density(aes(log(concentration), weight = white/sum(white), fill = "1990", color = "1990"), alpha = 0.4, data[data$year == 1990, ]) +
  geom_density(aes(log(concentration), weight = white/sum(white), fill = "2000", color = "2000"), alpha = 0.4, data[data$year == 2000, ]) +
  geom_density(aes(log(concentration), weight = white/sum(white), fill = "2010", color = "2010"), alpha = 0.4, data[data$year == 2010, ]) +
  labs(x = "Log of Concentration", y = "Density", fill = "Legend") +
  guides(color = FALSE) + xlim(-6, 20) + ylim(0, 0.25)

ggplot() + 
  geom_density(aes(log(concentration), weight = black/sum(black), fill = "1990", color = "1990"), alpha = 0.4, data[data$year == 1990, ]) +
  geom_density(aes(log(concentration), weight = black/sum(black), fill = "2000", color = "2000"), alpha = 0.4, data[data$year == 2000, ]) +
  geom_density(aes(log(concentration), weight = black/sum(black), fill = "2010", color = "2010"), alpha = 0.4, data[data$year == 2010, ]) +
  labs(x = "Log of Concentration", y = "Density", fill = "Legend") +
  guides(color = FALSE) + xlim(-6, 20) + ylim(0, 0.25)
  
```


## Interacting Risk Cases
```{r}
ggplot(perc50) + 
  geom_ribbon(aes(x = year, ymax = log(blackh), ymin = log(blackl), fill = "black"), alpha = 0.3) + 
  geom_line(aes(x = year, y = log(blackh), fill = "black"), alpha = 0.3) + 
  geom_line(aes(x = year, y = log(whiteh), fill = "white"), alpha = 0.3) + 
  geom_line(aes(x = year, y = log(hisph), fill = "white"), alpha = 0.3) + 
  geom_ribbon(aes(x = year, ymax = log(whiteh), ymin = log(whitel), fill = "white"), alpha = 0.3) + 
  geom_ribbon(aes(x = year, ymax = log(hisph), ymin = log(hispl), fill = "hispanic"), alpha = 0.3)

ggplot(perc50) + 
  geom_ribbon(aes(x = year, ymax = blackh, ymin = blackl, fill = "black"), alpha = 0.3) + 
  geom_line(aes(x = year, y = blackh, fill = "black"), alpha = 0.3) + 
  geom_line(aes(x = year, y = whiteh, fill = "white"), alpha = 0.3) + 
  geom_line(aes(x = year, y = hisph, fill = "white"), alpha = 0.3) + 
  geom_ribbon(aes(x = year, ymax = whiteh, ymin = whitel, fill = "white"), alpha = 0.3) + 
  geom_ribbon(aes(x = year, ymax = hisph, ymin = hispl, fill = "hispanic"), alpha = 0.3)
```


## Geographic Changes in Exposure

## Quantile Regression
```{r}
test = rq(log(concentration) ~ year + (black/pop) + (white/pop) + (hispanic/pop) + (other/pop), tau = 0.5, data = hisp_data)
```

