# Conclusion {#conclusion}

In the literature there is disagreement on the verifiability of environmental racism, with some studies finding extraordinary differences in environments experienced by minorities, others hypothesizing that none were found due to the geographic unit of analysis, and yet others claiming that all toxicity differences can be accounted for by other geographic or economic characteristics - not race. 

The most fundamental criticisms of the field of environmental justice are twofold. Firstly, that due to the prevalence of geographically and temporally focused studies, no results are generalizable, and the field cannot be thought of as showing a true difference in minority and white populations as national groups. In the previously quoted words of one author, all that can be surmised from the field as a whole is "that in some specific areas, some groups in the population may in some instances live closer to some selected environmental hazards." (Anderton et al., 1994) I attempt to address this by using data spanning the entire nation, over an unusually long period of time. This data, by definition, can be thought of as representative of minority and white populations as national groups, and differences cannot be attributed to random change in a temporal snapshot of data. 

The second large criticism of the field is that racial differences in experienced environmental hazard are manufactured. Rather than reflecting a 'true difference' in experiences by race, it's stated that positive results can only be attributed to a reflection of "known economic inequities in residential patterns around existing industrial centers" (Szasz and Meuser, 1997), effectively concluding that these inequalities are a class issue - not a race issue. While they are correct in stating that inequities we see are not necessarily related to "prejudicial choice[s]" in siting of new facilities, there is a disparity in experiences, regardless of intent or cause. One explanation of toxicity disparities currently discussed in the literature relies upon the idea of direct and conscious racism in siting and polluting, yet the differences in experienced toxicity are environmental racism irrespective of the accuracy of that theory. 

Regardless of the cause behind environmental racism, the data I have presented appears to tangibly show distinctly different distributions of toxicity experienced by minority groups. The strength of this analysis relies on the length of RSEI data available, which has yet to be examined over such a long period. The longest temporal period examined was spanning the years of 1970 to 1995, as conducted by Been and Gupta. The longest recent study of toxicity using RSEI data covered the years of 1995 to 2004, 15 fewer years than the currently presented data. The broad scope of this work allows statements that cover the entire population over a length period, but limitations in data don't allow for statements covering all toxicity, only that consistently measured by the TRI program. Additionally, no inferences can be made on the impact this toxicity has, in terms of health or impact on lifestyle. 

This work has yet to include geographic variables (such as census region, population density, suburb vs. city, level of manufacturing, availability of jobs, housing market, access to transportation etc.), which may add to both the explanatory and predictive power of this analysis. Potential areas for improvement include using more detailed income data, using small area estimation to generate cross tabulations at lower geographic levels, and creating models with more local data in order to better understand the differences attributable to race. Currently presented results may be useful as a baseline on the current trends in environmental inequality at a national scale, and as a more interpretable individual level description of the experiences of various racial and ethnic groups.